# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:math.* OR cat:nlin.* OR cat:stat.* OR cat:eess.* OR cat:cs.*'

# 検索キーワード
keywords:
        plasma: 10
        nuclear fusion: 10
        simulation: 3
        disruption: 3
        field line tracing: 3
        tokamak: 5
        eddy current: 5
        MHD equilibrium: 5
        Resonant Magnetic Perturbation: 5
        Resistive Wall Mode: 5
        JT-60SA: 5
        VMEC: 10
        adjoint method: 5

# 通知の閾値
score_threshold: 5

iop_rss_url:
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0741-3335
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0029-5515
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0963-0252
