# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:math.* OR cat:nlin.* OR cat:stat.* OR cat:eess.* OR cat:cs.*'

# 検索キーワード
keywords:
        plasma: 3
        fusion: 3
        simulation: 2
        tokamak: 5
        disruption: 5
        eddy current: 5
        field line tracing: 5
        resonant magnetic perturbation: 5
        resistive wall mode: 5

# 通知の閾値
score_threshold: 5
